### ISSUE TITLE
Podman.munki blocking apps

### ISSUE THREAD

**Issue by dhmoore** [autopkg/gregneagle-recipes#15]
https://github.com/containers/podman/releases says "VMs created by podman machine can now use the native Apple hypervisor (applehv) when run on MacOS." The blocking apps array for this recipe include only qemu paths. Podman 5.0 is not included as part of the latest Podman release, but when it is, you'll probably want to add this to blocking apps: /opt/podman/bin/vfkit

**Comment by dhmoore** [comment]
Also from the 5.0 release notes: QEMU is no longer a supported VM provider for podman machine on Mac. Instead, the native Apple hypervisor is supported.

**Comment by gregneagle** [comment]
Untested, but this should address: https://github.com/autopkg/gregneagle-recipes/commit/5d6d41237f2e4d325610d1a0cd2d9e81b3c870a6

**Comment by gregneagle** [comment]
No feedback (positive or negative); going to assume this is no longer an issue.
