### ISSUE TITLE
[ERROR] EOF when reading a line using AutoPkgr

### ISSUE THREAD

**Issue by tkimpton** [autopkg/gregneagle-recipes#4]
Hi Greg

I have been trying FirefoxAutoconfig.pkg with AutoPkgr and i am getting the error

A Python exception occurred during the execution of autopkg, see the system log for more details.
[ERROR] EOF when reading a line.

Im trying on 10.12.5 and have tried different machines.

Would it be possible for you to have a look?

Thanks

Tim

**Comment by gregneagle** [comment]
I don't use AutoPkgr, but the recipe works fine for me with the autopkg command-line tool. I think you will need to provide more detail/context around your issue if we want to troubleshoot it.

**Comment by tkimpton** [comment]
Hi Greg

Thought i just did. I will try the command-line tool instead

**Comment by tkimpton** [comment]
Thanks for the info works without issue :)
