### ISSUE TITLE
Bluejeans Plugin 

### ISSUE THREAD

**Issue by jonbrown21** [autopkg/gregneagle-recipes#5]
```
Processing BluejeansPlugin.munki.recipe...
No match found on URL: https://bluejeans.com/downloads
Failed.
```
After doing some digging it seems like this is no longer a thing bluejeans is developing. Its been a while since I ran this recipe just flagging it.

**Comment by gregneagle** [comment]
Closing this issue as the Bluejeans Plugin recipes were removed several months ago.
