### ISSUE TITLE
SuspiciousPackage.xip recipes should probably be removed

### ISSUE THREAD

**Issue by arubdesu** [autopkg/gregneagle-recipes#8]
Hitting the download variants URL redirects to https://www.mothersruin.com/software/SuspiciousPackage/faq.html#dmg

> Since more than two years have elapsed since Apple made this change, we have stopped providing an alternate XIP format download. Please use the disk image download instead.

**Comment by gregneagle** [comment]
Agreed. There's no clean way to deprecate recipes, so maybe a painful disappearance makes sense.

**Comment by gregneagle** [comment]
Addressed here: https://github.com/autopkg/gregneagle-recipes/commit/0b99bbd69402f4ac861269c0aae3ec2382a440d6
